In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import os
import csv
import math
import string
from collections import Counter
import re
import warnings
warnings.filterwarnings("ignore")

# datascience libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

# sklearn library
from sklearn.datasets import load_files
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score

# algorithms
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier, BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neural_network import MLPClassifier

In [ ]:
para_level_Dataset_features=pd.read_csv('/content/drive/MyDrive/Research/Final Experimentation Datasets/Topic wise advanced/Moral Lesson/para_stylometry_features.csv')


In [ ]:
para_level_Dataset_features

File Names  total_words  \
0     /content/drive/MyDrive/Research/Final Experime...         1109   
1     /content/drive/MyDrive/Research/Final Experime...          775   
2     /content/drive/MyDrive/Research/Final Experime...         1083   
3     /content/drive/MyDrive/Research/Final Experime...         1618   
4     /content/drive/MyDrive/Research/Final Experime...         1612   
...                                                 ...          ...   
3571  /content/drive/MyDrive/Research/Final Experime...         2109   
3572  /content/drive/MyDrive/Research/Final Experime...         1409   
3573  /content/drive/MyDrive/Research/Final Experime...         1069   
3574  /content/drive/MyDrive/Research/Final Experime...         1094   
3575  /content/drive/MyDrive/Research/Final Experime...         1979   

      total_lines  empty_line_count  average_word_length  ratio_of_3  \
0               1                 0             3.547340        0.26   
1              19                 9             3.500645        0.19   
2              23                11             3.430286        0.25   
3              23                11             3.715080        0.22   
4              31                15             3.323201        0.26   
...           ...               ...                  ...         ...   
3571           25                12             3.518255        0.24   
3572           25                12             3.542938        0.27   
3573           21                10             3.708138        0.24   
3574           27                13             3.666362        0.24   
3575           33                16             3.821627        0.21   

      ratio_of_4  ratio_of_long_words  total_unique_words  punctuation_count  \
0           0.21                 0.02                 568                 75   
1           0.23                 0.01                 310                 39   
2           0.25                 0.01                 511                 70   
3           0.23                 0.02                 673                114   
4           0.23                 0.01                 558                105   
...          ...                  ...                 ...                ...   
3571        0.25                 0.01                 717                131   
3572        0.22                 0.01                 621                109   
3573        0.24                 0.04                 522                 93   
3574        0.16                 0.03                 430                 58   
3575        0.26                 0.03                 828                135   

      ...  average_paragraph_length  min_paragraph_length  \
0     ...               5051.000000                  5051   
1     ...                347.800000                   100   
2     ...                398.916667                    89   
3     ...                635.250000                   224   
4     ...                434.562500                   199   
...   ...                       ...                   ...   
3571  ...                732.000000                   160   
3572  ...                491.384615                   256   
3573  ...                457.090909                   225   
3574  ...                363.714286                   219   
3575  ...                560.294118                   115   

      max_paragraph_length  average_words_per_paragraph  \
0                     5051                  1109.000000   
1                      631                    77.500000   
2                      805                    90.250000   
3                     1337                   134.833333   
4                      668                   100.750000   
...                    ...                          ...   
3571                  1605                   162.230769   
3572                   695                   108.384615   
3573                   656                    97.181818   
3574                   644     

In [ ]:
# drop column of file names
para_level_Dataset_features = para_level_Dataset_features.drop(['File Names'], axis=1)


In [ ]:
# convert Para-Level Label column values into digits
label_encoder = LabelEncoder()
para_level_Dataset_features['Label'] = label_encoder.fit_transform(para_level_Dataset_features['Label'])

In [ ]:
#all features
X_all=para_level_Dataset_features.drop(['Label'], axis=1)
y=para_level_Dataset_features['Label']
X_all_train, X_all_test, y_train, y_test = train_test_split(X_all, y, test_size=0.2, random_state=42)
# Convert X_train and X_test to NumPy arrays
X_all_train_np = np.array(X_all_train)
X_all_test_np = np.array(X_all_test)

# Ensure the arrays are contiguous
X_all_train_np = np.ascontiguousarray(X_all_train_np)
X_all_test_np = np.ascontiguousarray(X_all_test_np)

In [ ]:
#word level
X_word=para_level_Dataset_features.iloc[:, 0:10].values
X_word_train, X_word_test, y_train, y_test = train_test_split(X_word, y, test_size=0.2, random_state=42)
# Convert X_train and X_test to NumPy arrays
X_word_train_np = np.array(X_word_train)
X_word_test_np = np.array(X_word_test)

# Ensure the arrays are contiguous
X_word_train_np = np.ascontiguousarray(X_word_train_np)
X_word_test_np = np.ascontiguousarray(X_word_test_np)

In [ ]:
#Character level
X_char=para_level_Dataset_features.iloc[:, 10:26].values
X_char_train, X_char_test, y_train, y_test = train_test_split(X_char, y, test_size=0.2, random_state=42)
# Convert X_train and X_test to NumPy arrays
X_char_train_np = np.array(X_char_train)
X_char_test_np = np.array(X_char_test)

# Ensure the arrays are contiguous
X_char_train_np = np.ascontiguousarray(X_char_train_np)
X_char_test_np = np.ascontiguousarray(X_char_test_np)

In [ ]:
#Sen level
X_sen=para_level_Dataset_features.iloc[:, 26:33].values
X_sen_train, X_sen_test, y_train, y_test = train_test_split(X_sen, y, test_size=0.2, random_state=42)
# Convert X_train and X_test to NumPy arrays
X_sen_train_np = np.array(X_sen_train)
X_sen_test_np = np.array(X_sen_test)

# Ensure the arrays are contiguous
X_sen_train_np = np.ascontiguousarray(X_sen_train_np)
X_sen_test_np = np.ascontiguousarray(X_sen_test_np)

In [ ]:
#para+doc+tex
X_oth=para_level_Dataset_features.iloc[:, 33:].values
X_oth_train, X_oth_test, y_train, y_test = train_test_split(X_oth, y, test_size=0.2, random_state=42)
# Convert X_train and X_test to NumPy arrays
X_oth_train_np = np.array(X_oth_train)
X_oth_test_np = np.array(X_oth_test)

# Ensure the arrays are contiguous
X_oth_train_np = np.ascontiguousarray(X_oth_train_np)
X_oth_test_np = np.ascontiguousarray(X_oth_test_np)

##### 1 Apply Machine Learning Algorithms on  Para-Level Dataset

In [ ]:
# Initialize classifiers
logreg = LogisticRegression()
dtree = DecisionTreeClassifier()
rf = RandomForestClassifier()
svm = SVC()
knn = KNeighborsClassifier()
nb = GaussianNB()
lda = LinearDiscriminantAnalysis()
mlp = MLPClassifier(max_iter=1000)  # Adjust max_iter based on convergence
xgb = GradientBoostingClassifier()


In [ ]:
# Create a voting classifier
voting_clf = VotingClassifier(estimators=[
    ('logreg', logreg),
    ('dtree', dtree),
    ('rf', rf),
    ('svm', svm),
    ('knn', knn),
    ('nb', nb),
    ('lda', lda),
    ('mlp', mlp),
    ('xgb', xgb)
], voting='hard')

##### 1.1 word level

In [ ]:
#training
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    clf.fit(X_word_train_np, y_train)


In [ ]:
#testing
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, voting_clf]
y_pred_all = []

for clf in classifiers:
    y_pred = clf.predict(X_word_test_np)
    y_pred_all.append(y_pred)


In [ ]:
from sklearn.metrics import confusion_matrix

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_word_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_word_test_np)

    # Calculate confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Print the confusion matrix for each classifier
    print(f"Confusion matrix for {clf.__class__.__name__}:\n{cm}\n")


Confusion matrix for LogisticRegression:
[[259 107]
 [ 96 254]]

Confusion matrix for DecisionTreeClassifier:
[[341  25]
 [ 25 325]]

Confusion matrix for RandomForestClassifier:
[[350  16]
 [ 11 339]]

Confusion matrix for SVC:
[[336  30]
 [162 188]]

Confusion matrix for KNeighborsClassifier:
[[301  65]
 [ 41 309]]

Confusion matrix for GaussianNB:
[[352  14]
 [240 110]]

Confusion matrix for LinearDiscriminantAnalysis:
[[289  77]
 [106 244]]

Confusion matrix for MLPClassifier:
[[310  56]
 [182 168]]

Confusion matrix for GradientBoostingClassifier:
[[337  29]
 [ 31 319]]

Confusion matrix for VotingClassifier:
[[350  16]
 [ 68 282]]



In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_word_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_word_test_np)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Print metrics with bold headings
    print(f"\nMetrics for {clf.__class__.__name__}:")
    print(f"**Accuracy:** {accuracy:.4f}")
    print(f"**Recall:** {recall:.4f}")
    print(f"**Precision:** {precision:.4f}")
    print(f"**F1 Score:** {f1:.4f}")



Metrics for LogisticRegression:
**Accuracy:** 0.7165
**Recall:** 0.7257
**Precision:** 0.7036
**F1 Score:** 0.7145

Metrics for DecisionTreeClassifier:
**Accuracy:** 0.9218
**Recall:** 0.9171
**Precision:** 0.9224
**F1 Score:** 0.9198

Metrics for RandomForestClassifier:
**Accuracy:** 0.9609
**Recall:** 0.9771
**Precision:** 0.9448
**F1 Score:** 0.9607

Metrics for SVC:
**Accuracy:** 0.7318
**Recall:** 0.5371
**Precision:** 0.8624
**F1 Score:** 0.6620

Metrics for KNeighborsClassifier:
**Accuracy:** 0.8520
**Recall:** 0.8829
**Precision:** 0.8262
**F1 Score:** 0.8536

Metrics for GaussianNB:
**Accuracy:** 0.6453
**Recall:** 0.3143
**Precision:** 0.8871
**F1 Score:** 0.4641

Metrics for LinearDiscriminantAnalysis:
**Accuracy:** 0.7444
**Recall:** 0.6971
**Precision:** 0.7601
**F1 Score:** 0.7273

Metrics for MLPClassifier:
**Accuracy:** 0.5293
**Recall:** 0.0371
**Precision:** 1.0000
**F1 Score:** 0.0716

Metrics for GradientBoostingClassifier:
**Accuracy:** 0.9148
**Recall:** 0.9114
*

In [ ]:
#training
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    clf.fit(X_word_train_np, y_train)

##### 1.2 Character Level

In [ ]:
#training
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    clf.fit(X_char_train_np, y_train)

In [ ]:
#testing
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, voting_clf]
y_pred_all = []

for clf in classifiers:
    y_pred = clf.predict(X_char_test_np)
    y_pred_all.append(y_pred)


In [ ]:
from sklearn.metrics import confusion_matrix

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_char_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_char_test_np)

    # Calculate confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Print the confusion matrix for each classifier
    print(f"Confusion matrix for {clf.__class__.__name__}:\n{cm}\n")

Confusion matrix for LogisticRegression:
[[290  76]
 [ 53 297]]

Confusion matrix for DecisionTreeClassifier:
[[337  29]
 [ 24 326]]

Confusion matrix for RandomForestClassifier:
[[355  11]
 [ 12 338]]

Confusion matrix for SVC:
[[343  23]
 [171 179]]

Confusion matrix for KNeighborsClassifier:
[[283  83]
 [ 44 306]]

Confusion matrix for GaussianNB:
[[350  16]
 [163 187]]

Confusion matrix for LinearDiscriminantAnalysis:
[[287  79]
 [ 37 313]]

Confusion matrix for MLPClassifier:
[[358   8]
 [160 190]]

Confusion matrix for GradientBoostingClassifier:
[[342  24]
 [ 21 329]]

Confusion matrix for VotingClassifier:
[[346  20]
 [ 27 323]]



In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_char_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_char_test_np)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Print metrics with bold headings
    print(f"\nMetrics for {clf.__class__.__name__}:")
    print(f"**Accuracy:** {accuracy:.4f}")
    print(f"**Recall:** {recall:.4f}")
    print(f"**Precision:** {precision:.4f}")
    print(f"**F1 Score:** {f1:.4f}")


Metrics for LogisticRegression:
**Accuracy:** 0.8198
**Recall:** 0.8486
**Precision:** 0.7962
**F1 Score:** 0.8216

Metrics for DecisionTreeClassifier:
**Accuracy:** 0.9302
**Recall:** 0.9314
**Precision:** 0.9261
**F1 Score:** 0.9288

Metrics for RandomForestClassifier:
**Accuracy:** 0.9735
**Recall:** 0.9714
**Precision:** 0.9742
**F1 Score:** 0.9728

Metrics for SVC:
**Accuracy:** 0.7291
**Recall:** 0.5114
**Precision:** 0.8861
**F1 Score:** 0.6486

Metrics for KNeighborsClassifier:
**Accuracy:** 0.8226
**Recall:** 0.8743
**Precision:** 0.7866
**F1 Score:** 0.8281

Metrics for GaussianNB:
**Accuracy:** 0.7500
**Recall:** 0.5343
**Precision:** 0.9212
**F1 Score:** 0.6763

Metrics for LinearDiscriminantAnalysis:
**Accuracy:** 0.8380
**Recall:** 0.8943
**Precision:** 0.7985
**F1 Score:** 0.8437

Metrics for MLPClassifier:
**Accuracy:** 0.6117
**Recall:** 0.2086
**Precision:** 0.9865
**F1 Score:** 0.3443

Metrics for GradientBoostingClassifier:
**Accuracy:** 0.9372
**Recall:** 0.9400
*

##### 1.3 Sen Level

In [ ]:
#training
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    clf.fit(X_sen_train_np, y_train)


In [ ]:

#testing
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, voting_clf]
y_pred_all = []
for clf in classifiers:
    y_pred = clf.predict(X_sen_test_np)
    y_pred_all.append(y_pred)


In [ ]:
from sklearn.metrics import confusion_matrix

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_sen_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_sen_test_np)

    # Calculate confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Print the confusion matrix for each classifier
    print(f"Confusion matrix for {clf.__class__.__name__}:\n{cm}\n")

Confusion matrix for LogisticRegression:
[[232 134]
 [135 215]]

Confusion matrix for DecisionTreeClassifier:
[[329  37]
 [ 36 314]]

Confusion matrix for RandomForestClassifier:
[[340  26]
 [ 19 331]]

Confusion matrix for SVC:
[[245 121]
 [123 227]]

Confusion matrix for KNeighborsClassifier:
[[303  63]
 [ 40 310]]

Confusion matrix for GaussianNB:
[[135 231]
 [ 78 272]]

Confusion matrix for LinearDiscriminantAnalysis:
[[218 148]
 [118 232]]

Confusion matrix for MLPClassifier:
[[252 114]
 [ 88 262]]

Confusion matrix for GradientBoostingClassifier:
[[318  48]
 [ 52 298]]

Confusion matrix for VotingClassifier:
[[299  67]
 [ 52 298]]



In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_sen_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_sen_test_np)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Print metrics with bold headings
    print(f"\nMetrics for {clf.__class__.__name__}:")
    print(f"**Accuracy:** {accuracy:.4f}")
    print(f"**Recall:** {recall:.4f}")
    print(f"**Precision:** {precision:.4f}")
    print(f"**F1 Score:** {f1:.4f}")



Metrics for LogisticRegression:
**Accuracy:** 0.6243
**Recall:** 0.6143
**Precision:** 0.6160
**F1 Score:** 0.6152

Metrics for DecisionTreeClassifier:
**Accuracy:** 0.8911
**Recall:** 0.8914
**Precision:** 0.8864
**F1 Score:** 0.8889

Metrics for RandomForestClassifier:
**Accuracy:** 0.9260
**Recall:** 0.9371
**Precision:** 0.9136
**F1 Score:** 0.9252

Metrics for SVC:
**Accuracy:** 0.6592
**Recall:** 0.6486
**Precision:** 0.6523
**F1 Score:** 0.6504

Metrics for KNeighborsClassifier:
**Accuracy:** 0.8561
**Recall:** 0.8857
**Precision:** 0.8311
**F1 Score:** 0.8575

Metrics for GaussianNB:
**Accuracy:** 0.5684
**Recall:** 0.7771
**Precision:** 0.5408
**F1 Score:** 0.6377

Metrics for LinearDiscriminantAnalysis:
**Accuracy:** 0.6285
**Recall:** 0.6629
**Precision:** 0.6105
**F1 Score:** 0.6356

Metrics for MLPClassifier:
**Accuracy:** 0.7095
**Recall:** 0.5657
**Precision:** 0.7795
**F1 Score:** 0.6556

Metrics for GradientBoostingClassifier:
**Accuracy:** 0.8603
**Recall:** 0.8514
*

##### 1.4 Para+doc+text

In [ ]:
#training
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    clf.fit(X_oth_train_np, y_train)

In [ ]:
#testing
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, voting_clf]
y_pred_all = []

for clf in classifiers:
    y_pred = clf.predict(X_oth_test_np)
    y_pred_all.append(y_pred)


In [ ]:
from sklearn.metrics import confusion_matrix

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_oth_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_oth_test_np)

    # Calculate confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Print the confusion matrix for each classifier
    print(f"Confusion matrix for {clf.__class__.__name__}:\n{cm}\n")

Confusion matrix for LogisticRegression:
[[365   1]
 [  0 350]]

Confusion matrix for DecisionTreeClassifier:
[[366   0]
 [  0 350]]

Confusion matrix for RandomForestClassifier:
[[366   0]
 [  0 350]]

Confusion matrix for SVC:
[[305  61]
 [ 92 258]]

Confusion matrix for KNeighborsClassifier:
[[302  64]
 [ 23 327]]

Confusion matrix for GaussianNB:
[[366   0]
 [  0 350]]

Confusion matrix for LinearDiscriminantAnalysis:
[[313  53]
 [121 229]]

Confusion matrix for MLPClassifier:
[[366   0]
 [  0 350]]

Confusion matrix for GradientBoostingClassifier:
[[366   0]
 [  0 350]]

Confusion matrix for VotingClassifier:
[[366   0]
 [  0 350]]



In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_oth_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_oth_test_np)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Print metrics with bold headings
    print(f"\nMetrics for {clf.__class__.__name__}:")
    print(f"**Accuracy:** {accuracy:.4f}")
    print(f"**Recall:** {recall:.4f}")
    print(f"**Precision:** {precision:.4f}")
    print(f"**F1 Score:** {f1:.4f}")


Metrics for LogisticRegression:
**Accuracy:** 0.9986
**Recall:** 1.0000
**Precision:** 0.9972
**F1 Score:** 0.9986

Metrics for DecisionTreeClassifier:
**Accuracy:** 1.0000
**Recall:** 1.0000
**Precision:** 1.0000
**F1 Score:** 1.0000

Metrics for RandomForestClassifier:
**Accuracy:** 1.0000
**Recall:** 1.0000
**Precision:** 1.0000
**F1 Score:** 1.0000

Metrics for SVC:
**Accuracy:** 0.7863
**Recall:** 0.7371
**Precision:** 0.8088
**F1 Score:** 0.7713

Metrics for KNeighborsClassifier:
**Accuracy:** 0.8785
**Recall:** 0.9343
**Precision:** 0.8363
**F1 Score:** 0.8826

Metrics for GaussianNB:
**Accuracy:** 1.0000
**Recall:** 1.0000
**Precision:** 1.0000
**F1 Score:** 1.0000

Metrics for LinearDiscriminantAnalysis:
**Accuracy:** 0.7570
**Recall:** 0.6543
**Precision:** 0.8121
**F1 Score:** 0.7247

Metrics for MLPClassifier:
**Accuracy:** 0.9958
**Recall:** 1.0000
**Precision:** 0.9915
**F1 Score:** 0.9957

Metrics for GradientBoostingClassifier:
**Accuracy:** 1.0000
**Recall:** 1.0000
*

##### 1.5 All Level

In [ ]:
#training
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    clf.fit(X_all_train_np, y_train)

In [ ]:
#testing
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, voting_clf]
y_pred_all = []

for clf in classifiers:
    y_pred = clf.predict(X_all_test_np)
    y_pred_all.append(y_pred)

In [ ]:
from sklearn.metrics import confusion_matrix

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_all_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_all_test_np)

    # Calculate confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Print the confusion matrix for each classifier
    print(f"Confusion matrix for {clf.__class__.__name__}:\n{cm}\n")


Confusion matrix for LogisticRegression:
[[318  48]
 [ 40 310]]

Confusion matrix for DecisionTreeClassifier:
[[348  18]
 [ 16 334]]

Confusion matrix for RandomForestClassifier:
[[360   6]
 [  3 347]]

Confusion matrix for SVC:
[[334  32]
 [ 86 264]]

Confusion matrix for KNeighborsClassifier:
[[327  39]
 [ 11 339]]

Confusion matrix for GaussianNB:
[[349  17]
 [135 215]]

Confusion matrix for LinearDiscriminantAnalysis:
[[331  35]
 [ 36 314]]

Confusion matrix for MLPClassifier:
[[317  49]
 [ 16 334]]

Confusion matrix for GradientBoostingClassifier:
[[355  11]
 [  3 347]]

Confusion matrix for VotingClassifier:
[[355  11]
 [ 17 333]]



In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_all_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_all_test_np)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Print metrics with bold headings
    print(f"\nMetrics for {clf.__class__.__name__}:")
    print(f"**Accuracy:** {accuracy:.4f}")
    print(f"**Recall:** {recall:.4f}")
    print(f"**Precision:** {precision:.4f}")
    print(f"**F1 Score:** {f1:.4f}")


Metrics for LogisticRegression:
**Accuracy:** 0.8771
**Recall:** 0.8857
**Precision:** 0.8659
**F1 Score:** 0.8757

Metrics for DecisionTreeClassifier:
**Accuracy:** 0.9581
**Recall:** 0.9600
**Precision:** 0.9545
**F1 Score:** 0.9573

Metrics for RandomForestClassifier:
**Accuracy:** 0.9860
**Recall:** 0.9943
**Precision:** 0.9775
**F1 Score:** 0.9858

Metrics for SVC:
**Accuracy:** 0.8352
**Recall:** 0.7543
**Precision:** 0.8919
**F1 Score:** 0.8173

Metrics for KNeighborsClassifier:
**Accuracy:** 0.9302
**Recall:** 0.9686
**Precision:** 0.8968
**F1 Score:** 0.9313

Metrics for GaussianNB:
**Accuracy:** 0.7877
**Recall:** 0.6143
**Precision:** 0.9267
**F1 Score:** 0.7388

Metrics for LinearDiscriminantAnalysis:
**Accuracy:** 0.9008
**Recall:** 0.8971
**Precision:** 0.8997
**F1 Score:** 0.8984

Metrics for MLPClassifier:
**Accuracy:** 0.9274
**Recall:** 0.9057
**Precision:** 0.9435
**F1 Score:** 0.9242

Metrics for GradientBoostingClassifier:
**Accuracy:** 0.9804
**Recall:** 0.9914
*