In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os
import csv
import math
import string
from collections import Counter
import re
import warnings
warnings.filterwarnings("ignore")

# datascience libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

# sklearn library
from sklearn.datasets import load_files
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score

# algorithms
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier, BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neural_network import MLPClassifier

In [ ]:
para_level_Dataset_features=pd.read_csv('/content/drive/MyDrive/Research/Final Experimentation Datasets/Topic wise advanced/National Event/para_stylometry_features.csv')


In [ ]:
# drop column of file names
para_level_Dataset_features = para_level_Dataset_features.drop(['File Names'], axis=1)


In [ ]:
# convert Para-Level Label column values into digits
label_encoder = LabelEncoder()
para_level_Dataset_features['Label'] = label_encoder.fit_transform(para_level_Dataset_features['Label'])

In [ ]:
#all features
X_all=para_level_Dataset_features.drop(['Label'], axis=1)
y=para_level_Dataset_features['Label']
X_all_train, X_all_test, y_train, y_test = train_test_split(X_all, y, test_size=0.2, random_state=42)
# Convert X_train and X_test to NumPy arrays
X_all_train_np = np.array(X_all_train)
X_all_test_np = np.array(X_all_test)

# Ensure the arrays are contiguous
X_all_train_np = np.ascontiguousarray(X_all_train_np)
X_all_test_np = np.ascontiguousarray(X_all_test_np)

In [ ]:
#word level
X_word=para_level_Dataset_features.iloc[:, 0:10].values
X_word_train, X_word_test, y_train, y_test = train_test_split(X_word, y, test_size=0.2, random_state=42)
# Convert X_train and X_test to NumPy arrays
X_word_train_np = np.array(X_word_train)
X_word_test_np = np.array(X_word_test)

# Ensure the arrays are contiguous
X_word_train_np = np.ascontiguousarray(X_word_train_np)
X_word_test_np = np.ascontiguousarray(X_word_test_np)

In [ ]:
#Character level
X_char=para_level_Dataset_features.iloc[:, 10:26].values
X_char_train, X_char_test, y_train, y_test = train_test_split(X_char, y, test_size=0.2, random_state=42)
# Convert X_train and X_test to NumPy arrays
X_char_train_np = np.array(X_char_train)
X_char_test_np = np.array(X_char_test)

# Ensure the arrays are contiguous
X_char_train_np = np.ascontiguousarray(X_char_train_np)
X_char_test_np = np.ascontiguousarray(X_char_test_np)

In [ ]:
#Sen level
X_sen=para_level_Dataset_features.iloc[:, 26:33].values
X_sen_train, X_sen_test, y_train, y_test = train_test_split(X_sen, y, test_size=0.2, random_state=42)
# Convert X_train and X_test to NumPy arrays
X_sen_train_np = np.array(X_sen_train)
X_sen_test_np = np.array(X_sen_test)

# Ensure the arrays are contiguous
X_sen_train_np = np.ascontiguousarray(X_sen_train_np)
X_sen_test_np = np.ascontiguousarray(X_sen_test_np)

In [ ]:
#para+doc+tex
X_oth=para_level_Dataset_features.iloc[:, 33:].values
X_oth_train, X_oth_test, y_train, y_test = train_test_split(X_oth, y, test_size=0.2, random_state=42)
# Convert X_train and X_test to NumPy arrays
X_oth_train_np = np.array(X_oth_train)
X_oth_test_np = np.array(X_oth_test)

# Ensure the arrays are contiguous
X_oth_train_np = np.ascontiguousarray(X_oth_train_np)
X_oth_test_np = np.ascontiguousarray(X_oth_test_np)

##### 1 Apply Machine Learning Algorithms on  Para-Level Dataset

In [ ]:
# Initialize classifiers
logreg = LogisticRegression()
dtree = DecisionTreeClassifier()
rf = RandomForestClassifier()
svm = SVC()
knn = KNeighborsClassifier()
nb = GaussianNB()
lda = LinearDiscriminantAnalysis()
mlp = MLPClassifier(max_iter=1000)  # Adjust max_iter based on convergence
xgb = GradientBoostingClassifier()


In [ ]:
# Create a voting classifier
voting_clf = VotingClassifier(estimators=[
    ('logreg', logreg),
    ('dtree', dtree),
    ('rf', rf),
    ('svm', svm),
    ('knn', knn),
    ('nb', nb),
    ('lda', lda),
    ('mlp', mlp),
    ('xgb', xgb)
], voting='hard')

##### 1.1 word level

In [ ]:
#training
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    clf.fit(X_word_train_np, y_train)


In [ ]:
#testing
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, voting_clf]
y_pred_all = []

for clf in classifiers:
    y_pred = clf.predict(X_word_test_np)
    y_pred_all.append(y_pred)


In [ ]:
from sklearn.metrics import confusion_matrix

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_word_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_word_test_np)

    # Calculate confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Print the confusion matrix for each classifier
    print(f"Confusion matrix for {clf.__class__.__name__}:\n{cm}\n")


Confusion matrix for LogisticRegression:
[[36 21]
 [ 8 43]]

Confusion matrix for DecisionTreeClassifier:
[[55  2]
 [ 0 51]]

Confusion matrix for RandomForestClassifier:
[[55  2]
 [ 0 51]]

Confusion matrix for SVC:
[[51  6]
 [ 9 42]]

Confusion matrix for KNeighborsClassifier:
[[54  3]
 [ 1 50]]

Confusion matrix for GaussianNB:
[[55  2]
 [19 32]]

Confusion matrix for LinearDiscriminantAnalysis:
[[42 15]
 [ 7 44]]

Confusion matrix for MLPClassifier:
[[55  2]
 [31 20]]

Confusion matrix for GradientBoostingClassifier:
[[56  1]
 [ 0 51]]

Confusion matrix for VotingClassifier:
[[56  1]
 [ 0 51]]



In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_word_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_word_test_np)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Print metrics with bold headings
    print(f"\nMetrics for {clf.__class__.__name__}:")
    print(f"**Accuracy:** {accuracy:.4f}")
    print(f"**Recall:** {recall:.4f}")
    print(f"**Precision:** {precision:.4f}")
    print(f"**F1 Score:** {f1:.4f}")



Metrics for LogisticRegression:
**Accuracy:** 0.7315
**Recall:** 0.8431
**Precision:** 0.6719
**F1 Score:** 0.7478

Metrics for DecisionTreeClassifier:
**Accuracy:** 0.9815
**Recall:** 1.0000
**Precision:** 0.9623
**F1 Score:** 0.9808

Metrics for RandomForestClassifier:
**Accuracy:** 0.9907
**Recall:** 1.0000
**Precision:** 0.9808
**F1 Score:** 0.9903

Metrics for SVC:
**Accuracy:** 0.8611
**Recall:** 0.8235
**Precision:** 0.8750
**F1 Score:** 0.8485

Metrics for KNeighborsClassifier:
**Accuracy:** 0.9630
**Recall:** 0.9804
**Precision:** 0.9434
**F1 Score:** 0.9615

Metrics for GaussianNB:
**Accuracy:** 0.8056
**Recall:** 0.6275
**Precision:** 0.9412
**F1 Score:** 0.7529

Metrics for LinearDiscriminantAnalysis:
**Accuracy:** 0.7963
**Recall:** 0.8627
**Precision:** 0.7458
**F1 Score:** 0.8000

Metrics for MLPClassifier:
**Accuracy:** 0.7130
**Recall:** 1.0000
**Precision:** 0.6220
**F1 Score:** 0.7669

Metrics for GradientBoostingClassifier:
**Accuracy:** 0.9907
**Recall:** 1.0000
*

In [ ]:
#training
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    clf.fit(X_word_train_np, y_train)

##### 1.2 Character Level

In [ ]:
#training
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    clf.fit(X_char_train_np, y_train)

In [ ]:
#testing
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, voting_clf]
y_pred_all = []

for clf in classifiers:
    y_pred = clf.predict(X_char_test_np)
    y_pred_all.append(y_pred)


In [ ]:
from sklearn.metrics import confusion_matrix

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_char_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_char_test_np)

    # Calculate confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Print the confusion matrix for each classifier
    print(f"Confusion matrix for {clf.__class__.__name__}:\n{cm}\n")

Confusion matrix for LogisticRegression:
[[52  5]
 [ 8 43]]

Confusion matrix for DecisionTreeClassifier:
[[55  2]
 [ 0 51]]

Confusion matrix for RandomForestClassifier:
[[56  1]
 [ 0 51]]

Confusion matrix for SVC:
[[52  5]
 [11 40]]

Confusion matrix for KNeighborsClassifier:
[[52  5]
 [ 1 50]]

Confusion matrix for GaussianNB:
[[56  1]
 [23 28]]

Confusion matrix for LinearDiscriminantAnalysis:
[[50  7]
 [ 8 43]]

Confusion matrix for MLPClassifier:
[[45 12]
 [ 7 44]]

Confusion matrix for GradientBoostingClassifier:
[[56  1]
 [ 1 50]]

Confusion matrix for VotingClassifier:
[[56  1]
 [ 1 50]]



In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_char_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_char_test_np)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Print metrics with bold headings
    print(f"\nMetrics for {clf.__class__.__name__}:")
    print(f"**Accuracy:** {accuracy:.4f}")
    print(f"**Recall:** {recall:.4f}")
    print(f"**Precision:** {precision:.4f}")
    print(f"**F1 Score:** {f1:.4f}")


Metrics for LogisticRegression:
**Accuracy:** 0.8796
**Recall:** 0.8431
**Precision:** 0.8958
**F1 Score:** 0.8687

Metrics for DecisionTreeClassifier:
**Accuracy:** 0.9722
**Recall:** 0.9804
**Precision:** 0.9615
**F1 Score:** 0.9709

Metrics for RandomForestClassifier:
**Accuracy:** 0.9907
**Recall:** 1.0000
**Precision:** 0.9808
**F1 Score:** 0.9903

Metrics for SVC:
**Accuracy:** 0.8519
**Recall:** 0.7843
**Precision:** 0.8889
**F1 Score:** 0.8333

Metrics for KNeighborsClassifier:
**Accuracy:** 0.9444
**Recall:** 0.9804
**Precision:** 0.9091
**F1 Score:** 0.9434

Metrics for GaussianNB:
**Accuracy:** 0.7778
**Recall:** 0.5490
**Precision:** 0.9655
**F1 Score:** 0.7000

Metrics for LinearDiscriminantAnalysis:
**Accuracy:** 0.8611
**Recall:** 0.8431
**Precision:** 0.8600
**F1 Score:** 0.8515

Metrics for MLPClassifier:
**Accuracy:** 0.9352
**Recall:** 0.9608
**Precision:** 0.9074
**F1 Score:** 0.9333

Metrics for GradientBoostingClassifier:
**Accuracy:** 0.9815
**Recall:** 0.9804
*

##### 1.3 Sen Level

In [ ]:
#training
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    clf.fit(X_sen_train_np, y_train)


In [ ]:

#testing
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, voting_clf]
y_pred_all = []
for clf in classifiers:
    y_pred = clf.predict(X_sen_test_np)
    y_pred_all.append(y_pred)


In [ ]:
from sklearn.metrics import confusion_matrix

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_sen_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_sen_test_np)

    # Calculate confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Print the confusion matrix for each classifier
    print(f"Confusion matrix for {clf.__class__.__name__}:\n{cm}\n")

Confusion matrix for LogisticRegression:
[[49  8]
 [ 3 48]]

Confusion matrix for DecisionTreeClassifier:
[[55  2]
 [ 4 47]]

Confusion matrix for RandomForestClassifier:
[[55  2]
 [ 0 51]]

Confusion matrix for SVC:
[[40 17]
 [ 5 46]]

Confusion matrix for KNeighborsClassifier:
[[51  6]
 [ 1 50]]

Confusion matrix for GaussianNB:
[[43 14]
 [ 3 48]]

Confusion matrix for LinearDiscriminantAnalysis:
[[48  9]
 [ 7 44]]

Confusion matrix for MLPClassifier:
[[41 16]
 [ 0 51]]

Confusion matrix for GradientBoostingClassifier:
[[55  2]
 [ 2 49]]

Confusion matrix for VotingClassifier:
[[52  5]
 [ 1 50]]



In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_sen_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_sen_test_np)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Print metrics with bold headings
    print(f"\nMetrics for {clf.__class__.__name__}:")
    print(f"**Accuracy:** {accuracy:.4f}")
    print(f"**Recall:** {recall:.4f}")
    print(f"**Precision:** {precision:.4f}")
    print(f"**F1 Score:** {f1:.4f}")



Metrics for LogisticRegression:
**Accuracy:** 0.8981
**Recall:** 0.9412
**Precision:** 0.8571
**F1 Score:** 0.8972

Metrics for DecisionTreeClassifier:
**Accuracy:** 0.9444
**Recall:** 0.9216
**Precision:** 0.9592
**F1 Score:** 0.9400

Metrics for RandomForestClassifier:
**Accuracy:** 0.9722
**Recall:** 0.9608
**Precision:** 0.9800
**F1 Score:** 0.9703

Metrics for SVC:
**Accuracy:** 0.7963
**Recall:** 0.9020
**Precision:** 0.7302
**F1 Score:** 0.8070

Metrics for KNeighborsClassifier:
**Accuracy:** 0.9352
**Recall:** 0.9804
**Precision:** 0.8929
**F1 Score:** 0.9346

Metrics for GaussianNB:
**Accuracy:** 0.8426
**Recall:** 0.9412
**Precision:** 0.7742
**F1 Score:** 0.8496

Metrics for LinearDiscriminantAnalysis:
**Accuracy:** 0.8519
**Recall:** 0.8627
**Precision:** 0.8302
**F1 Score:** 0.8462

Metrics for MLPClassifier:
**Accuracy:** 0.8148
**Recall:** 0.6471
**Precision:** 0.9429
**F1 Score:** 0.7674

Metrics for GradientBoostingClassifier:
**Accuracy:** 0.9630
**Recall:** 0.9608
*

##### 1.4 Para+doc+text

In [ ]:
#training
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    clf.fit(X_oth_train_np, y_train)

In [ ]:
#testing
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, voting_clf]
y_pred_all = []

for clf in classifiers:
    y_pred = clf.predict(X_oth_test_np)
    y_pred_all.append(y_pred)


In [ ]:
from sklearn.metrics import confusion_matrix

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_oth_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_oth_test_np)

    # Calculate confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Print the confusion matrix for each classifier
    print(f"Confusion matrix for {clf.__class__.__name__}:\n{cm}\n")

Confusion matrix for LogisticRegression:
[[53  4]
 [ 0 51]]

Confusion matrix for DecisionTreeClassifier:
[[57  0]
 [ 0 51]]

Confusion matrix for RandomForestClassifier:
[[57  0]
 [ 0 51]]

Confusion matrix for SVC:
[[51  6]
 [21 30]]

Confusion matrix for KNeighborsClassifier:
[[48  9]
 [ 3 48]]

Confusion matrix for GaussianNB:
[[57  0]
 [ 0 51]]

Confusion matrix for LinearDiscriminantAnalysis:
[[49  8]
 [ 3 48]]

Confusion matrix for MLPClassifier:
[[51  6]
 [ 6 45]]

Confusion matrix for GradientBoostingClassifier:
[[57  0]
 [ 0 51]]

Confusion matrix for VotingClassifier:
[[57  0]
 [ 0 51]]



In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_oth_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_oth_test_np)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Print metrics with bold headings
    print(f"\nMetrics for {clf.__class__.__name__}:")
    print(f"**Accuracy:** {accuracy:.4f}")
    print(f"**Recall:** {recall:.4f}")
    print(f"**Precision:** {precision:.4f}")
    print(f"**F1 Score:** {f1:.4f}")


Metrics for LogisticRegression:
**Accuracy:** 0.9630
**Recall:** 1.0000
**Precision:** 0.9273
**F1 Score:** 0.9623

Metrics for DecisionTreeClassifier:
**Accuracy:** 1.0000
**Recall:** 1.0000
**Precision:** 1.0000
**F1 Score:** 1.0000

Metrics for RandomForestClassifier:
**Accuracy:** 1.0000
**Recall:** 1.0000
**Precision:** 1.0000
**F1 Score:** 1.0000

Metrics for SVC:
**Accuracy:** 0.7500
**Recall:** 0.5882
**Precision:** 0.8333
**F1 Score:** 0.6897

Metrics for KNeighborsClassifier:
**Accuracy:** 0.8889
**Recall:** 0.9412
**Precision:** 0.8421
**F1 Score:** 0.8889

Metrics for GaussianNB:
**Accuracy:** 1.0000
**Recall:** 1.0000
**Precision:** 1.0000
**F1 Score:** 1.0000

Metrics for LinearDiscriminantAnalysis:
**Accuracy:** 0.8981
**Recall:** 0.9412
**Precision:** 0.8571
**F1 Score:** 0.8972

Metrics for MLPClassifier:
**Accuracy:** 0.7593
**Recall:** 0.5490
**Precision:** 0.9032
**F1 Score:** 0.6829

Metrics for GradientBoostingClassifier:
**Accuracy:** 1.0000
**Recall:** 1.0000
*

##### 1.5 All Level

In [ ]:
#training
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    clf.fit(X_all_train_np, y_train)

In [ ]:
#testing
classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, voting_clf]
y_pred_all = []

for clf in classifiers:
    y_pred = clf.predict(X_all_test_np)
    y_pred_all.append(y_pred)

In [ ]:
from sklearn.metrics import confusion_matrix

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_all_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_all_test_np)

    # Calculate confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Print the confusion matrix for each classifier
    print(f"Confusion matrix for {clf.__class__.__name__}:\n{cm}\n")


Confusion matrix for LogisticRegression:
[[54  3]
 [ 0 51]]

Confusion matrix for DecisionTreeClassifier:
[[55  2]
 [ 1 50]]

Confusion matrix for RandomForestClassifier:
[[57  0]
 [ 0 51]]

Confusion matrix for SVC:
[[46 11]
 [ 8 43]]

Confusion matrix for KNeighborsClassifier:
[[56  1]
 [ 2 49]]

Confusion matrix for GaussianNB:
[[49  8]
 [ 6 45]]

Confusion matrix for LinearDiscriminantAnalysis:
[[55  2]
 [ 0 51]]

Confusion matrix for MLPClassifier:
[[55  2]
 [ 1 50]]

Confusion matrix for GradientBoostingClassifier:
[[57  0]
 [ 0 51]]

Confusion matrix for VotingClassifier:
[[57  0]
 [ 0 51]]



In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

classifiers = [logreg, dtree, rf, svm, knn, nb, lda, mlp, xgb, voting_clf]

for clf in classifiers:
    # Fit the classifier to the training data
    clf.fit(X_all_train_np, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_all_test_np)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Print metrics with bold headings
    print(f"\nMetrics for {clf.__class__.__name__}:")
    print(f"**Accuracy:** {accuracy:.4f}")
    print(f"**Recall:** {recall:.4f}")
    print(f"**Precision:** {precision:.4f}")
    print(f"**F1 Score:** {f1:.4f}")


Metrics for LogisticRegression:
**Accuracy:** 0.9722
**Recall:** 1.0000
**Precision:** 0.9444
**F1 Score:** 0.9714

Metrics for DecisionTreeClassifier:
**Accuracy:** 0.9722
**Recall:** 0.9804
**Precision:** 0.9615
**F1 Score:** 0.9709

Metrics for RandomForestClassifier:
**Accuracy:** 1.0000
**Recall:** 1.0000
**Precision:** 1.0000
**F1 Score:** 1.0000

Metrics for SVC:
**Accuracy:** 0.8241
**Recall:** 0.8431
**Precision:** 0.7963
**F1 Score:** 0.8190

Metrics for KNeighborsClassifier:
**Accuracy:** 0.9722
**Recall:** 0.9608
**Precision:** 0.9800
**F1 Score:** 0.9703

Metrics for GaussianNB:
**Accuracy:** 0.8704
**Recall:** 0.8824
**Precision:** 0.8491
**F1 Score:** 0.8654

Metrics for LinearDiscriminantAnalysis:
**Accuracy:** 0.9815
**Recall:** 1.0000
**Precision:** 0.9623
**F1 Score:** 0.9808

Metrics for MLPClassifier:
**Accuracy:** 0.9444
**Recall:** 0.9608
**Precision:** 0.9245
**F1 Score:** 0.9423

Metrics for GradientBoostingClassifier:
**Accuracy:** 1.0000
**Recall:** 1.0000
*